ms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views
urlpatterns=[
    path('ms/<str:user>', views.ms_index, name="ms_index"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("shopsite.urls")),
    path("", include("ms.urls")),
    path('admin/', admin.site.urls),
    path("", include("allauth.urls")), #most important
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('comment/', include('comment.urls')),
    path("", include("django.contrib.auth.urls")),
    path('api/', include('comment.api.urls')),  # only required for API Framework

    
]

shopsite/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", views.index, name="index"),
    path("Music/", views.m, name="m"),
    path("basket/", views.basket, name="basket"),
    path("user/<str:name>/", views.user, name="user"),
    path("search/<str:search>/", views.search, name="search"),
    path("<int:product_id>/", views.detail, name="detail"),
    path("buy/<int:product_id>/", views.order, name="order"),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('user_menu/', views.user_menu, name='user_menu'),
    path('create_product/', views.create_product, name='create_product'),
    path('user_orders/', views.user_orders, name='user_orders'),
    path('delete/<int:product_id>/', views.delete, name="delete"),
    path('order_buy/', views.order_buy, name="order_buy"),
    path('basket/delete/<int:pr_id>/', views.dele, name='delete_from_basket'),
    path('basket/history', views.basket_history, name="basket_history"),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopsite/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from django.urls import reverse
pr = None
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product_name = models.CharField(max_length=30)
    text = models.TextField()
    big_text = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    photo = models.ImageField(upload_to='static/image',blank=True)
    comments = GenericRelation(Comment)




class Order(models.Model):
    
    product = models.ManyToManyField(Product,through='OrderItem', null=True)
    name = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    email = models.EmailField(max_length=254)
    status = models.CharField(max_length=30 ,null=True)

class OrderItem(models.Model):
    class Meta:
        db_table = 'OrderItem2'

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        return f"{self.order} - {self.product} - Quantity: {self.quantity}"


class like(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30)
    like_range = models.IntegerField(
        null=True,
        validators=[
            MinValueValidator(1, message="dont like."),
            MaxValueValidator(5, message="like."),
        ]
    )
    coment = models.CharField(max_length=32, blank=True, null=True)

ms/forms.py
from django import forms

shopsite/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import Order

class ChangeOrderStatusForm(forms.Form):
    order_id = forms.IntegerField(widget=forms.HiddenInput())


# from .models import Product
class OrderForm(forms.Form):
    pass


class QuantityForm(forms.Form):
    quantity = forms.IntegerField(
        min_value=1,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'min': 1})
    )

class CreateProductForm(forms.Form):
    product_name = forms.CharField(label="Назва", max_length=30)
    text = forms.CharField(label="Текст", widget=forms.Textarea)
    big_text = forms.CharField(label="Довгий текст", widget=forms.Textarea)
    price = forms.DecimalField(label="Ціна", max_digits=8, decimal_places=2)
    photo = forms.ImageField(label="Фото",required=False, widget=forms.FileInput)

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price is None or price <= -0.00000000000000001:
            raise forms.ValidationError("Ціна повинна бути більше нуля.")
        return price

    # def clean_photo(self):
    #     photo = self.cleaned_data.get('photo')
    #     if not photo:
    #         raise forms.ValidationError("Фото обов'язково.")
    #     return photo

class DeleteForm(forms.Form):
    pass


class EditProductForm(forms.Form):
    product_name = forms.CharField(label="назва", max_length=30)
    text = forms.CharField(widget=forms.Textarea)
    big_text = forms.CharField(widget=forms.Textarea)
    price = forms.DecimalField(max_digits=8, decimal_places=2)
    photo = forms.ImageField(required=False)





class LikeForm(forms.Form):
    product_id = forms.IntegerField()  # Assuming you want to enter the product ID

    # Name field with max length of 30 characters
    name = forms.CharField(max_length=30)

    # Like range field as an IntegerField with validators
    like_range = forms.IntegerField(
        validators=[
            MinValueValidator(1, message="dont like"),
            MaxValueValidator(5, message="like"),
        ]
    )

    # Comment field with max length of 30 characters (optional)
    comment = forms.CharField(max_length=30, required=False)

ms/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import Data, Text,ms_user
from django.db.models import Q
from django.shortcuts import render ,get_object_or_404 ,redirect
from django.http import HttpResponse ,HttpRequest, HttpResponseForbidden
from django.core.exceptions import FieldError
from django.contrib.auth.decorators import login_required


def ms_index(request, user):
    # Retrieve the User object based on its primary key (pk=user)
    user_obj = get_object_or_404(User, username=user)
    

    try:
        # Attempt to get the Data object related to the current user
        current_data = Data.objects.get(name=request.user, from_name=user_obj)
        text = current_data.text.values_list('text', flat=True)
    except Data.DoesNotExist:
        # If the Data object doesn't exist, set a default value for text
        text = "Default text"

    print(text)
    # Get the ms_user object related to the current user
    try:
        current_user_ms = ms_user.objects.get(name=request.user)
        img = current_user_ms.photo
    except ms_user.DoesNotExist:
        # If there is no related ms_user object for the current user, set img to None or provide a default value
        img = None


    contact = current_user_ms.contact.all()

    return render(request, 'ms_index.html', {"user": user, "img": img, "text": text,"contact":contact,})

shopsite/views.py
from django.db.models import Q
from django.shortcuts import render ,get_object_or_404 ,redirect
from django.http import HttpResponse ,HttpRequest, HttpResponseForbidden
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_protect
from .models import Product, Order, like,OrderItem
from .forms import OrderForm ,CreateProductForm, DeleteForm ,EditProductForm, LikeForm,QuantityForm,ChangeOrderStatusForm
from django.contrib.auth.models import User
from django.core.exceptions import FieldError
from django.contrib.auth.decorators import login_required
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Sum
from ms.models import ms_user
from star_ratings.models import Rating
@login_required
def img(request):

    try:
        current_user_ms = ms_user.objects.get(name=request.user)
        img = current_user_ms.photo
    except ms_user.DoesNotExist:
        # If there is no related ms_user object for the current user, set img to None or provide a default value
        img = None
    return img

import random

def index(request):
    latest_product_list = Product.objects.all()
    
    # Select 2 unique random products from the list
    try:
        selected_products = random.sample(list(latest_product_list), k=9)
    except Exception as e:
        try:
            selected_products = random.sample(list(latest_product_list), k=6)
        except Exception as e:
            try:
                selected_products = random.sample(list(latest_product_list), k=3)
            except Exception as e:
                try:
                    selected_products = random.sample(list(latest_product_list), k=1)
                except Exception as e:
                    selected_products = random.sample(list(latest_product_list), k=0)
        
    context = {
        'latest_product_list': selected_products,
        'img': img(request),
    }

    return render(request, 'index.html', context)





@csrf_protect
def basket(request):
    user_orders = Order.objects.filter(status="basket",name=request.user).distinct()
    for order in user_orders:
        total_price = order.product.all().aggregate(Sum('price'))['price__sum']
        order.total_price = total_price

    if request.method == 'POST':
        form = QuantityForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            product_id = request.POST.get('product_id')  # Get the product ID from the request
            product = get_object_or_404(Product, pk=product_id)

            # Create a new order with status='basket' for the current user if it doesn't exist
            new_order, created = Order.objects.get_or_create(name=request.user, status='basket')

            # Add the product to the order with the selected quantity
            order_item, created = OrderItem.objects.get_or_create(order=new_order, product=product)
            order_item.quantity = quantity
            order_item.save()

            return redirect('basket')  # Redirect back to the basket page after adding the product

    else:

        # Pass the initial value to the form
        form = QuantityForm()

    return render(request, 'basket.html', {'user_orders': user_orders, 'OrderItem': OrderItem, 'form': form,'img':img(request),})

    



def user(request, name):
    user = User.objects.get(username=name)
    email = user.email
    objects = Product.objects.filter(user__username__contains=name)
    context = {
        'name': name,
        'user': user,
        'objects': objects,
        'img':img(request),
    }
    return render(request, 'user.html', context)


def search(request, search):
    try:
        search_integer = int(search)  # Assuming 'search' is an integer, handle it appropriately
    except ValueError:
        search_integer = None

    # Use separate Q objects for each field search
    q_product_name = Q(product_name__icontains=search)
    q_text = Q(text__icontains=search)
    q_price = Q(price__icontains=search_integer) if search_integer is not None else Q()
    q_big_text = Q(big_text__icontains=search)
    q_username = Q(user__username__icontains=search)

    objects = Product.objects.filter(q_product_name | q_text | q_price | q_big_text | q_username)
    context = {
        'objects': objects,
        'img':img(request),
    }
    return render(request, 'search.html', context)


@csrf_protect
def detail(request, product_id):
    prod = get_object_or_404(Product, pk=product_id)
    likes = like.objects.order_by("-id")[:5]

    # if request.method == 'POST':
    #     form = LikeForm(request.POST)
    #     if form.is_valid():
    #         # Get the form data
    #         product_id = form.cleaned_data['product_id']
    #         name = form.cleaned_data['name']
    #         like_range = form.cleaned_data['like_range']
    #         comment = form.cleaned_data['comment']
            
    #         # Save the data to the database
    #         product = get_object_or_404(Product, pk=product_id)
    #         like = like(product=product, name=name, like_range=like_range, comment=comment)
    #         like.save()

    # else:
    #     form = LikeForm()

    return render(request, "detail.html", {"product": prod,  "likes": likes,'img':img(request),})






# def results(request, question_id):
#     response = "You're looking at the results of product %s."
#     return HttpResponse(response % question_id)


# def vote(request, question_id):
#     return HttpResponse("You're voting on product %s." % question_id)





@csrf_protect
def order(request, product_id):
    prod = get_object_or_404(Product, pk=product_id)

    # Get the current user
    user = request.user

    # Create a new order with status='basket' for the current user if it doesn't exist
    new_order, created = Order.objects.get_or_create(name=user, status='basket')

    # Add the product to the order
    if new_order.product.filter(pk=prod.pk).exists():
        # The product is already in the order, update its quantity or do nothing
        order_item = OrderItem.objects.filter(order=new_order, product=prod).first()
        if order_item:
            # Increment the quantity if needed, or perform any other actions related to the existing item
            order_item.quantity += 1
            order_item.save()
    else:
        # The product is not in the order, create a new OrderItem and add it to the order
        order_item = OrderItem.objects.create(order=new_order, product=prod)

    # if request.method == 'POST':
    #     form = OrderForm(request.POST)
    #     if form.is_valid():
    #         # Perform any additional actions here if needed

    #         # Redirect to a success page or perform other actions
    #         # For example, redirecting to a thank you page after placing an order
    #         return redirect('../../../../../%s' % product_id)

    # else:
    #     form = OrderForm()

    return render(request, "order.html", {"product": prod,'img':img(request),})


@csrf_protect
def order_buy(request):
    # Assuming 'user' is the name of the authenticated user
    user = request.user

    # Get the order for the authenticated user with status='basket'
    user_order = get_object_or_404(Order, name=user, status='basket')

    # Update the status to 'of' (assuming 'of' is a valid status)
    user_order.status = 'не відправлино'
    user_order.save()

    # Print the updated order (optional)
    print(user_order)

    return HttpResponse("<h1 >корзину відправлено</h1>")





@csrf_protect
def dele(request, pr_id):
    # Get the authenticated user
    user = request.user

    # Get the order for the authenticated user with status='basket'
    user_order = Order.objects.get(name=user, status='basket')

    # pr_id = "Product object (%s)" %pr_id
    user_order.product.remove(pr_id)
    user_order.save()
    return HttpResponse("<h1>продукт з корзини видалено</h1>")




@login_required
def user_menu(request):
    search = request.user.username
    try:
        search_integer = int(search)  # Assuming 'search' is an integer, handle it appropriately
    except ValueError:
        search_integer = None

    # Use separate Q objects for each field search
    q_product_name = Q(product_name__icontains=search)
    q_text = Q(text__icontains=search)
    q_price = Q(price__icontains=search_integer) if search_integer is not None else Q()
    q_big_text = Q(big_text__icontains=search)
    q_username = Q(user__username__icontains=search)

    objects = Product.objects.filter(q_username)
    context = {
        'objects': objects,
        'img':img(request),
    }
    return render(request, 'user_menu.html', context)






def create_product(request):
    if request.method == 'POST':
        form = CreateProductForm(request.POST, request.FILES)
        if form.is_valid():
            product_name = form.cleaned_data['product_name']
            text = form.cleaned_data['text']
            big_text = form.cleaned_data['big_text']
            price = form.cleaned_data['price']
            photo = form.cleaned_data['photo']

            # Assuming you have a logged-in user, you can get the user instance from request
            user = request.user

            # Now create the product with the correct user instance
            prod = Product(user=user, product_name=product_name, text=text, big_text=big_text, price=price, photo=photo)
            prod.save()

            return redirect('../../../../user_menu/')
    else:
        form = CreateProductForm()

    return render(request, 'product_form.html', {'form': form,'img':img(request),})



@csrf_protect
def edit_product(request, product_id):
    prod = get_object_or_404(Product, pk=product_id)

    if request.user != prod.user:
        # If the logged-in user is not the owner of the product, return a forbidden response
        return HttpResponseForbidden("You don't have permission to edit this product.")

shopsite/templates/basket.html
{% extends "navbar.html" %}
{% block content %}
  	<h1>Basket</h1>
  	<a href="/order_buy"><p>Відправити корзину</p></a>
	<a href="history"><p>history</p></a>

  	{% for order in user_orders %}      

    	<ul>
      		{% for item in order.orderitem_set.all %}
        		<li>
					<p> 
						<form method="post" action="{% url 'basket' %}">
							{% csrf_token %}
							<input type="hidden" name="product_id" value="{{ item.product.pk }}"></input>
							<!-- {{ form }} -->
						<p><a href="delete/{{ item.product.pk }}/"><button type="button" class="btn-close" aria-label="Close"></button></a>{{ item.product.product_name }} - Price: {{ item.product.price }} - Quantity:<input type="number" name="quantity" class="form-control" min="1" required="" id="id_quantity" value="{{ item.quantity }}"></p>
							<button type="submit"></button>
						</form>
				
					</p>
					
       			</li>
      		{% endfor %}  
    	</ul>
  	{% endfor %}
{% endblock %}

shopsite/templates/basket_history.html
{% extends "navbar.html" %}
{% block content %}

<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><a href="/../../../../basket/">basket</a></li>
  </ul>
</div>

<h1>basket history</h1>

{% for order in user_orders %}
    <form method="post">
      {% csrf_token %}
      <input type="hidden" name="order_id" value="{{ order.id }}">
      <!-- {{ form.as_p }} -->
      <button type="submit">Update Status</button>
    </form>
    <p>Status: {{ order.status }}</p>
    <ul>
        {% for item in order.orderitem_set.all %}
            <li>{{ item.product.product_name }} - Price: {{ item.product.price }} - Quantity: {{ item.quantity }}</li>
        {% endfor %}
    </ul>

{% endfor %}
{% endblock %}

shopsite/templates/delete.html
{% extends "navbar.html" %}

{% block content %}
  <h1>Delete Product</h1>
  <p>Are you sure you want to delete the product "{{ product.product_name }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, Delete</button>
    <a href="{% url 'detail' product.id %}">No, Cancel</a>
  </form>
{% endblock %}

shopsite/templates/detail.html
{% extends "navbar.html" %}

{% block title %}{% endblock %}
{% block head %}
    {% load static %}
    {% load comment_tags %}

    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
{% endblock %}
{% load ratings %}
{% block content %}
    
    <div class="card mb-3" style="width: 100% ;height: 100%;">
        <div class="row g-0">
            <div class="col-md-4">
                {% if product.photo.url > "" %}
                    <img style="width: 100% ;height: 400px;" src="{{ product.photo.url }}" class="img-fluid rounded-start" alt="...">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h1 style="text-align: center" class="card-title">{{ product.product_name }}</h1>
                    <a href="{% url 'order' product.id %}">
                        <button class="btn btn-primary" type="button">добавити в корзину</button>
                    </a>
                    {% if request.user.is_authenticated and request.user.username == product.user.username %}
                        <a href="../../../../delete/{{ product.id }}">
                            <button type="submit" class="btn-close" aria-label="Close"></button>
                        </a>
                    {% endif %}
                    <a href="{% url 'edit_product' product.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                        </svg>
                    </a>
                    <p class="card-text">Ціна: {{ product.price }}</p>
                    <a href="../../../../../../user/{{ product.user }}">
                        <p class="card-text">Продавець: {{ product.user }} </p>
                    </a>
                    <div style="width:200px;" class="shadow-lg p-3 mb-5 bg-body-tertiary rounded">
                        <p class="card-text">{{ product.big_text }}</p>
                    </div>
                    {% ratings product %}
                    {% render_comments product request %}
                    
                </div>
            </div>
        </div>
    </div>

{% endblock %}

shopsite/templates/edit_product.html
{% extends "navbar.html" %}

{% block title %}{% endblock %}

{% block content %}
<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="/../../../../create_product/">create_product</a></li>
        <li class="list-group-item"><a href="../../../../../../user_menu/">user_menu</a></li>
        <li class="list-group-item"><a href="../../../../user_orders/">user_orders</a></li>
    </ul>
</div>

<div class="container">
    <h1>Edit Product</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock %}

shopsite/templates/index.html
{% extends "navbar.html" %}

{% block title %}{% endblock %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
      
        {% if latest_product_list %}
            {% for product in latest_product_list %}
                <div width="500px" height="500px" class="col">
                    <div class="card" style="width: 18rem;">
                        {% if product.photo.url > "" %}
                            <img src="{{ product.photo }}" class="card-img-top" alt={{ product.product_name }}>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.product_name }}</h5>
                            <p class="card-text">{{ product.text }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Ціна: {{ product.price }} лір</li>
                            <!-- <li class="list-group-item">Номер: {{ product.id }}</li> -->
                        </ul>
                        <div class="card-body">
                            <a href="{{ product.id }}" class="btn btn-primary">Перейти</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="card" aria-hidden="true">
                <div class="card-body">
                    <h5 class="card-title placeholder-glow">
                        <span class="placeholder col-6"></span>
                    </h5>
                    <p class="card-text placeholder-glow">
                        <span class="placeholder col-7"></span>
                        <span class="placeholder col-4"></span>
                        <span class="placeholder col-4"></span>
                        <span class="placeholder col-6"></span>
                        <span class="placeholder col-8"></span>
                    </p>
                    <a class="btn btn-primary disabled placeholder col-6"></a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

shopsite/templates/order.html
{% extends "navbar.html" %}

{% block title %}{% endblock %}

{% block content %}


	<p>добавлино в корзину</p>

{% endblock %}

shopsite/templates/product_form.html
{% extends "navbar.html" %}

{% block title %}Create Product{% endblock %}

{% block content %}
    <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><a href="/../../../../create_product/">create_product</a></li>
            <li class="list-group-item"><a href="../../../../../../user_menu/">user_menu</a></li>
            <li class="list-group-item"><a href="../../../../user_orders/">user_orders</a></li>
        </ul>
    </div>
    <div class="container">
        <h1>Create a New Product</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>



    

{% endblock %}

shopsite/templates/search.html
{% extends "navbar.html" %}

{% block title %}{% endblock %}

{% block content %}

    <div class="row row-cols-4 row-cols-md-5 g-4">
        {% for object in objects %}
            <div width="500px" height="500px" class="col">
                <div class="card" style="width: 18rem;">
                    {% if object.photo.url > "" %}
                        <img src="{{ object.photo.url }}" class="card-img-top" alt={{ object.photo.url }}>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ object.product_name }}</h5>
                        <p class="card-text">{{ object.text }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Ціна: {{ object.price }} лір</li>
                        <!-- <li class="list-group-item">Номер: {{ product.id }}</li> -->
                    </ul>
                    <div class="card-body">
                        <a href="{% url 'detail' object.id %}" class="btn btn-primary">Перейти</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

shopsite/templates/user.html
{% extends "navbar.html" %}
{% block head %}
    {% load static %}
    {% load comment_tags %}

    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
{% endblock %}
{% block title %}{% endblock %}
{% load ratings %}
{% block content %}

<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ name }}</li>
        <li class="list-group-item">email is hidden</li>
    </ul>
</div>

<div class="row row-cols-4 row-cols-md-5 g-4">
    {% for object in objects %}
        <div width="500px" height="500px" class="col">
            <div class="card" style="width: 18rem;">
                {% if product.photo.url > "" %}
                    <img  src="{{ object.photo.url }}" class="card-img-top" alt="{{ object.photo.url }}">
                {% endif %}
                <div class="card-body">
                    <h5 id="{{ object.product_name }}" class="card-title">{{ object.product_name }}</h5>
                    <p class="card-text">{{ object.text }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Ціна: {{ object.price }} грн</li>
                </ul>
                <div class="card-body">
                    {{ product.id }}
                    <a href="{{ product.id }}" class="btn btn-primary">Перейти</a>
                </div>
            </div>
        </div>
    {% endfor %}
    {% ratings user %}
    

{% endblock %}

shopsite/templates/user_menu.html
{% extends "navbar.html" %}

{% block title %}User Menu{% endblock %}

{% block content %}
    <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><a href="/../../../../create_product/">create_product</a></li>
            <li class="list-group-item"><a href="../../../../../../user_menu/">user_menu</a></li>
            <li class="list-group-item"><a href="../../../../user_orders/">user_orders</a></li>
        </ul>
    </div>
    <div class="row row-cols-4 row-cols-md-5 g-4">
        {% for object in objects %}
            <div width="500px" height="500px" class="col">
                <div class="card" style="width: 18rem;">
                   
                    <div class="card-body">
                        <h5 class="card-title">{{ object.product_name }}</h5>
                        <p class="card-text">{{ object.text }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Ціна: {{ object.price }} грн</li>
                        <!-- <li class="list-group-item">Номер: {{ product.id }}</li> -->
                    </ul>
                    <div class="card-body">
                        <a href="{% url 'detail' object.id %}" class="btn btn-primary">Перейти</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>



    

{% endblock %}

shopsite/templates/user_orders.html
{% extends "navbar.html" %}
{% block content %}

<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><a href="/../../../../create_product/">create_product</a></li>
    <li class="list-group-item"><a href="../../../../../../user_menu/">user_menu</a></li>
    <li class="list-group-item"><a href="../../../../user_orders/">user_orders</a></li>
  </ul>
</div>

<h1>User Orders</h1>

{% for order in user_orders %}
  <h2>Order : {{ order.name }}</h2>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="order_id" value="{{ order.id }}">
    <!-- {{ form.as_p }} -->
    <button type="submit">Update Status</button>
  </form>
  <p>Status: {{ order.status }}</p>
  <ul>
    {% for item in order.orderitem_set.all %}
      <li>{{ item.product.product_name }} - Price: {{ item.product.price }} - Quantity: {{ item.quantity }}</li>
    {% endfor %}
  </ul>
{% endfor %}
{% endblock %}